### ISSUE TITLE
API of packages could be improved

### ISSUE THREAD

**Issue by ILoveMyTortoise** [NoxOrg/Nox.Reference#8]
Currently, we have very generic imperfect interfaces that are not good enough for wide production usage. This needs to be discussed and improved.
Example: HolidayService should no more have a "year" param in its constructor

**Comment by AndreyDegtyarev** [comment]
Already implemented
Now usage looks like 
var countryHoliday = _worldDbContext.Holidays.Get(2023, "UA")!;
